package role

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"

	"github.com/lq5657/talkent/internal/llm"
)

type Service struct {
	llmClient llm.Client
	logger    *slog.Logger
}

func NewService(llmClient llm.Client, logger *slog.Logger) *Service {
	return &Service{
		llmClient: llmClient,
		logger:    logger,
	}
}

const recommendGoalsSystemPrompt = `你是一位训练目标推荐专家。根据用户提供的对话者角色描述，推荐适合用户的训练目标，帮助用户在与该对话者交流时提升应对和表达能力。
你必须严格以 JSON 格式输出，不要输出任何其他内容。格式如下：
{"goals": [{"name": "目标名称", "description": "目标描述"}]}`

func (s *Service) RecommendGoals(ctx context.Context, roleDesc string) ([]TrainingGoal, error) {
	if tmpl, ok := MatchTemplate(roleDesc); ok {
		s.logger.Info("goals matched from template", "type", tmpl.Type)
		return tmpl.DefaultGoals, nil
	}

	s.logger.Info("goals requiring LLM generation", "description_len", len(roleDesc))
	return s.generateGoals(ctx, roleDesc)
}

func (s *Service) generateGoals(ctx context.Context, roleDesc string) ([]TrainingGoal, error) {
	userPrompt := fmt.Sprintf("对话者角色描述：%s\n请推荐 3-5 个训练目标，帮助用户在与该对话者交流时提升表达能力。", roleDesc)

	messages := []llm.ChatMessage{
		{Role: llm.RoleSystem, Content: recommendGoalsSystemPrompt},
		{Role: llm.RoleUser, Content: userPrompt},
	}

	resp, err := s.llmClient.Chat(ctx, messages, &llm.ChatOptions{Temperature: 0.7})
	if err != nil {
		return nil, fmt.Errorf("llm generate goals: %w", err)
	}

	var result struct {
		Goals []TrainingGoal `json:"goals"`
	}
	if err := json.Unmarshal([]byte(resp.Content), &result); err != nil {
		return nil, fmt.Errorf("parse goals response: %w", err)
	}

	s.logger.Info("goals generated by LLM", "count", len(result.Goals))
	return result.Goals, nil
}

func (s *Service) RecommendDimensions(ctx context.Context, roleType RoleType, goals []TrainingGoal) ([]Dimension, error) {
	dims, ok := DimensionsForType(roleType)
	if ok {
		s.logger.Info("dimensions matched from table", "type", roleType, "count", len(dims))
		return dims, nil
	}

	s.logger.Info("dimensions not found in table, requiring LLM derivation", "type", roleType)
	return nil, fmt.Errorf("no dimensions found for role type %q, use DeriveDimensions instead", roleType)
}

const deriveDimensionsSystemPrompt = `你是一位分析维度设计专家。根据对话者角色描述和训练目标，推导适合的分析维度，用于评估用户在与该对话者交流时的表现。
你必须严格以 JSON 格式输出，不要输出任何其他内容。格式如下：
{"dimensions": [{"name": "维度名称", "description": "维度描述"}]}`

func (s *Service) DeriveDimensions(ctx context.Context, roleDesc string, goals []TrainingGoal) ([]Dimension, error) {
	goalNames := make([]string, len(goals))
	for i, g := range goals {
		goalNames[i] = g.Name
	}

	userPrompt := fmt.Sprintf("对话者角色：%s\n训练目标：%v\n请推导 3-7 个分析维度，用于评估用户与该对话者交流时的表现。", roleDesc, goalNames)

	messages := []llm.ChatMessage{
		{Role: llm.RoleSystem, Content: deriveDimensionsSystemPrompt},
		{Role: llm.RoleUser, Content: userPrompt},
	}

	resp, err := s.llmClient.Chat(ctx, messages, &llm.ChatOptions{Temperature: 0.7})
	if err != nil {
		return nil, fmt.Errorf("llm derive dimensions: %w", err)
	}

	var result struct {
		Dimensions []Dimension `json:"dimensions"`
	}
	if err := json.Unmarshal([]byte(resp.Content), &result); err != nil {
		return nil, fmt.Errorf("parse dimensions response: %w", err)
	}

	s.logger.Info("dimensions derived by LLM", "count", len(result.Dimensions))
	return result.Dimensions, nil
}
